return {
  "nvim-treesitter/nvim-treesitter",
  lazy = false,
  build = ":TSUpdate",
  opts = {
    ensure_installed = {
      "asm",
      "bash",
      "c",
      "cmake",
      "comment",
      "cpp",
      "css",
      "csv",
      "dot",
      "git_config",
      "git_rebase",
      "gitattributes",
      "gitcommit",
      "gitignore",
      "graphql",
      "html",
      "javascript",
      "jinja",
      "jinja_inline",
      "jsdoc",
      "json",
      "json5",
      "kitty",
      "lua",
      "luadoc",
      "make",
      "markdown",
      "markdown_inline",
      "powershell",
      "python",
      "regex",
      "rust",
      "sql",
      "svelte",
      "toml",
      "tsx",
      "typescript",
      "yaml",
      "zsh",
    },
    highlight = {
      enabled = true,
    },
    indent = {
      enabled = true,
    }
  },
  config = function(_, opts)
    require("nvim-treesitter").setup(opts)
  end,
}
